install.packages('optparse')
install.packages('dplyr')
install.packages('doParallel')
install.packages('rlist')
install.packages('xml2')
install.packages('remotes')
install.packages('BiocManager')
BiocManager::install('mumichae/tMAE')
BiocManager::install("FRASER")

options(timeout=0)
BiocManager::install("MafDb.gnomAD.r2.1.hs37d5")
BiocManager::install("MafDb.gnomAD.r2.1.GRCh38")
